### ISSUE TITLE
结果差异

### ISSUE THREAD

**Issue by hunaghuohui** [HKUDS/SSLRec#10]
感谢你的工作非常棒！但是我注意到一个问题，在这个框架中一些模型跑的结果，和模型原论文的原码的结果不一致，差别挺大的。这是什么原因呢

**Comment by Re-bin** [comment]
您好！

感谢您的关注和对SSLRec的使用，我们在实现框架的时候，尽量保持不同的模型之间，一些共用的算法/数据采样/训练策略模块是相同的，因此所有的算法可以在相同的环境下进行开发/训练验证/测试，从而保证同一套框架产生的结果具有公平性，可复现性以及可参考性。

由于存在实现细节或者是训练策略甚至数据采样上的差异，因此可能会与原论文/原码的实验结果的不同 :)

Best regards,
Xubin
