### ISSUE TITLE
是否支持大数据量

### ISSUE THREAD

**Issue by Yaoyuanzhou** [HKUDS/SSLRec#12]
你好，感谢你们的开源库，想问一下你们的开源库是否对大数据量进行支持呢，我的任务是做序列推荐，但现在我有几亿用户的历史数据量，请问你们支持如此大的数据量进行训练和推理么，如果支持的话请问需要注意什么呢

**Comment by Re-bin** [comment]
嗨，你好！

感谢关注，大数据量是一个很好的问题！
不过，在算法库的创建之初，主要考虑的是学术届常用的数据量大小，没有对承载极限做过压力测试。
针对于目前代码，我们在`data_utils/datasets_sequential.py`中的140行，将所有用户的历史交互数据以字典的形式存储，这样主要占用内存的资源，在训练的过程中，随机采样用户batch进行训练。

如果是几亿的数据量，首先对自身电脑的内存资源有一定的要求，其次，可以先在存储层面将几亿的用户进行均匀分块，在训练的过程中，先随机选择用户块，接着读取用户块到内存中，然后再对用户块内采样训练数据，这样可以缓解对内存的压力。

希望上述建议能对您有所帮助 :)

Best regards,
Xubin
