### ISSUE TITLE
Model leaderboard

### ISSUE THREAD

**Issue by Lightblues** [HKUDS/SSLRec#17]
您好!
请问SSL是否有相关模型+数据的实验结果 (最好能和原始论文的结果进行比较). 没有实验结果的话, 我们自己跑之后, 对于实验的指标没有可比较的对象~

祝好🙏

**Comment by Re-bin** [comment]
您好！

感谢对SSLRec的关注，我们在SSLRec的[ArXiv论文](https://arxiv.org/abs/2308.05697)中给每一个task提供了leaderboard结果。里面的数值，是对每个模型进行超参数搜索从而得到的最优效果，最优超参数并且已经写于每个模型的配置文件（yml文件）中。

论文中每一个leaderboard，是基于该task的一个数据集的结果，因此对每个模型的超参数搜索也是基于该数据集上的性能。您可以直接利用默认的配置超参数直接跑该数据集，就能得到leaderboard中的结果。

同时对于不同数据集，可能最优超参数会有所浮动。但是根据经验，其浮动不会太大，因此在调优时，每个模型的默认超参数都是可以用于参考的。

SSLRec中提供了grid search功能，其可以依据你指定的超参数范围，排列组合训练模型，并且保存结果。具体使用可以查看[用户指南](https://github.com/HKUDS/SSLRec/blob/main/docs/User%20Guide.md)中的Tune My Model章节。

希望上述回答可以帮助到你，如果还有任何问题，请告知我，感谢 :)
感谢你使用SSLRec，希望它能帮助到你的科研 :)

Best regards,
Xubin

**Comment by Lightblues** [comment]
感谢您的耐心回复! 
另, 在数据集上面还有想跟您探讨的地方: 我正在寻找 Sequential+KG 的数据, 但暂时没有发现直接可用的数据集. 

1. 第一点是好奇SSLRec中的数据是如何构造(处理)的? 是否和 [RecSysDatasets](https://github.com/RUCAIBox/RecSysDatasets) 中的数据相关? (发现相同数据名称的统计量并不同 (例如 AmazonBook, MovIe-lens 等)
2. 不知您是否处理过 RecBole 中的数据格式? 我构造  SRS+KG 的一个思路是利用 RecBole 框架中有包含KG的三个数据集 (MovieLens, Amazon-book, LFM-1b), 但在数据处理的时候发现其数据格式包装较深, 转换上遇到了困难😂 (之前在 #5 中给过建议, 不过RecBole的代码不太好懂orz

**Comment by Re-bin** [comment]
您好！

关于第一个问题，SSLRec中目前所存储的数据集是之前组内的工作积攒的数据集，一般是基于公开的原始数据进行处理的，处理过程遵循正常的流程，例如噪音过滤以及k-core等等。

关于第二个问题，目前暂时没有把RecBole的数据集转换成SSLRec的数据，RecBole是有一套自洽的交互数据格式。其实如果您需要处理SRS+KG的数据，个人认为可以先构建SRS的数据集，然后争对其中的items，再去构建KG数据集，最终的数据格式还是依据您自己常用的代码规范来构建。

希望上述回答能帮助到您 :)
