### ISSUE TITLE
增加social rec的模型

### ISSUE THREAD

**Issue by LDY911** [HKUDS/SSLRec#20]
您好，非常优秀的工作，贵组以后是否考虑增加social rec的模型，我看到DGNN还没有加入到这个框架中

**Comment by LDY911** [comment]
还有HGCL也没加入到框架

**Comment by Re-bin** [comment]
你好！👋

感谢关注，我们目前正在逐步增加新的模型，同时完善代码结构。

DGNN和HGCL也在计划之中 :)

Best regards,
Xubin

**Comment by LDY911** [comment]
> 你好！👋
> 
> 感谢关注，我们目前正在逐步增加新的模型，同时完善代码结构。
> 
> DGNN和HGCL也在计划之中 :)
> 
> Best regards, Xubin

好的，感谢回复
