### ISSUE TITLE
社会化推荐的smin模型总是loss为nan

### ISSUE THREAD

**Issue by LDY911** [HKUDS/SSLRec#21]
您好，我在使用SSLRec的SMIN模型时为何总是loss为nan，从第一代开始就是这样

**Comment by louiswng** [comment]
你好，你有对 smin.yml 进行更改吗？

**Comment by LDY911** [comment]
> 你好，你有对 smin.yml 进行更改吗？

您好，我没有改动模型结构和参数，我只是换成了自己的数据集，比如Ciao。我发现无论使用未处理数据还是删除掉低交互的user item，smin的损失函数都会nan，而且两个损失值都是nan

**Comment by Re-bin** [comment]
你好 👋

可能是在你的数据集上，模型运算过程中出现了inf或者nan导致的。

如方便，可先利用`torch.isnan()`和`torch.isinf()`排查一下是运算到哪一步最先出现了类似的值，以加速我们查找原因 :) 

Best regards,
Xubin
