### ISSUE TITLE
保存模型参数和优化器参数

### ISSUE THREAD

**Issue by CodeSniperYang** [HKUDS/SSLRec#22]
我想请教一下：保存模型的时候，同时保存优化器参数会不会更好？  

模型配置文件：只有save_model为True和False的选项，没有关于优化器的。
train.py文件：我看到train.py文件中的save_model函数，里面未对优化器保存。

还是说保存优化器参数的代码在其他地方写了，只是我没看见。

希望解答一下 😃

**Comment by Re-bin** [comment]
嗨 👋

感谢关注，目前的代码实现确实是只保存了训练好的模型的参数，然后关于优化器的参数例如learning rate之类的会保存在config中。不过在训练的时候，该次训练的所有超参数（包括优化器的）也会同时写在log文件里面方便参考 :)

Best regards,
Xubin

**Comment by CodeSniperYang** [comment]
嗷~~~我知道啦！感谢感谢
爱你们 ❤️
