### ISSUE TITLE
多行为推荐中的 MBSSL(SIGIR2023) 是否在计划中?  🌱 

### ISSUE THREAD

**Issue by DuTim** [HKUDS/SSLRec#25]
Multi-behavior Self-supervised Learning for Recommendation ( https://arxiv.org/pdf/2305.18238.pdf )  from  SIGIR'23
code link:     https://github.com/Scofield666/MBSSL
这个工作是否会添加到整个框架中? 
可以看到MBSSL通过整合SSL在多行为推荐中来进行优化, 非常具有代表性,
🚀 🚀

**Comment by Re-bin** [comment]
嗨，你好👋

感谢关注和指点，非常优秀的工作，我们会研究一下如何实现以及如何整合到SSLRec中 
如果有尝试整合的代码，也可以分享给我们，帮助快速整合，感谢您 :)

Best regards,
Xubin
