### ISSUE TITLE
Gumbel噪声的计算会出现-inf

### ISSUE THREAD

**Issue by wangxin211** [HKUDS/SSLRec#26]
在AutoCF代码中计算Gumble噪声时，会计算出-inf，进而导致infoloss的值变为inf
![image](https://github.com/HKUDS/SSLRec/assets/57390278/c427211f-f62f-479e-93bf-8de527955b43)

**Comment by Re-bin** [comment]
嗨，感谢关注👋

谢谢指正，可以尝试一下把42行替换成
```Python
noise = t.rand(scores.shape).cuda()
noise[noise == 0] = 1e-8
```
这样避免sample到0的情况，应该能解决问题 :)

Best regards,
Xubin
