### ISSUE TITLE
SimGCL: InfoNCE Loss Calculation Batch vs. Entire Embeddings

### ISSUE THREAD

**Issue by minholee-29cm** [HKUDS/SSLRec#28]
Hello, I found out that the current implementation of the InfoNCE loss in SimGCL seems to use the entire embeddings (user_embeds2 and item_embeds2), but the original paper suggests using batch embeddings.
Could you explain this difference?

**Comment by Re-bin** [comment]
Hi 👋!

Thank you for your interest and good question! Indeed, using either the batch embeddings or the entire embeddings to form the negative pairs in the InfoNCE loss is okay here. 

However, based on the theory of neural mutual information estimation, having a larger number of negative pairs contributes to a more stable estimation of mutual information during training. Therefore, in our implementation of SSLRec, we utilize the entire embeddings to form negative pairs with anchor views not only in SimGCL but also in methods like SGL and HCCF, ensuring a fair implementation.

I hope the above answers can help with your confusion :)

Best regards,
Xubin Ren

**Comment by minholee-29cm** [comment]
Aha, I see.
Thanks for your reply :)
