### ISSUE TITLE
关于评价指标

### ISSUE THREAD

**Issue by GKONGJ** [HKUDS/SSLRec#29]
您好，非常感谢团队共享的代码，并已经成功复现。但是复现过程中我发现多行为模型（例如CML，KMCLR）跑出来的评价指标值远低于原文。比如当数据集用IJCAI_15时. CML原文作者提供的项目代码NDGC@10能达到0.283，而我用贵团队的代码复现出来NDGC@10只有0.0224。作为一名小白，我想不明白为什么同一个模型同一个数据集且同样的评价指标会相差十倍，可否为我解答困惑？？感激不尽。

**Comment by Re-bin** [comment]
嗨，你好👋

感谢关注！这个是因为在SSLRec里面我们统一使用了all-rank（全排序）的测试方式，即对所有items进行排序，并且对top-k进行计算NDCG@K。在multi-behavior recommendation研究的原论文中（[MATN](https://arxiv.org/pdf/2110.04002.pdf), [CML](https://arxiv.org/pdf/2202.08523.pdf)）, 一般不是all-rank的测试策略，测试样本是由1个positive item+99个negative item构成（参考[代码209-215行](https://github.com/akaxlh/MATN/blob/master/labcode.py)），也就是100个items进行排序，然后对其中top-k进行计算指标。这个是产生差异的主要原因。

其次，可能模型超参数也会有所影响，目前我们是通过Retail Rocket数据集对多行为算法的超参数调到最优。不同的数据集对应的最优超参数可能也会有所不同。

然后回到您提出这个例子上面，全排序和100个items排序，直觉上来说后者这个测试策略下的指标会比前者更高一些。但只要所有的算法都在同一个策略下进行公平的性能测试，就可以保证公平性。

希望可以帮到你，如果有好的建议也欢迎随时反馈 :)

Best regards,
Xubin

**Comment by GKONGJ** [comment]
非常非常感谢您的快速回复！！很详细很清晰  我已经明白啦  也再次感谢您团队提供的代码对我的科研提供了极大的帮助  祝周末愉快！祝好~
