### ISSUE TITLE
关于多行为推荐中数据集问题

### ISSUE THREAD

**Issue by marqu22** [HKUDS/SSLRec#30]
您好，非常感谢贵团队共享的代码。
我对SSLRec中的多行为数据集存在一些疑问 。
以dataset/tmall 数据集为例：
1. meta_multi_single_beh_user_index_shuffle  的作用是什么 
2. train_mat_pv_buy.pkl ，train_mat_pv_fav_buy.pkl 等这类命名规则的文件分别代表什么含义
3. train_mat.pkl  与其他文件的关系。

非常期待您的回复！

此外，是否可以考虑增加一些简单的数据说明文档📝来增强框架代码的易读性。  
<img src="https://github.com/HKUDS/SSLRec/assets/163718116/5264eadc-ea5a-41fa-82d2-a2e546168dd5" style="max-width: 20%; height: auto;">

**Comment by Re-bin** [comment]
嗨，你好👋

感谢对SSLRec的关注！关于您所提出的问题：
1. `meta_multi_single_beh_user_index_shuffle` 是一个用户子集（以List存储的user index），这个是CML模型训练每个epoch中的second stage of training所用到的，其会对部分用户进行meta learning从而refine模型参数。用户的选取可以是交互丰富的用户从而防止模型在噪音上拟合；
2. `train_mat_pv_buy.pkl` 和 `train_mat_pv_fav_buy.pkl` 是user-item matrix，其记录的内容是多个behavior的交集 (meta-path) , 这个是HMG-CR模型所用到的。例如`train_mat_pv_buy.pkl`中的一个u-i pair，可以理解为其同时拥有pv和buy两种行为（pv是page view，fav是favorite的缩写）;
3. `train_mat.pkl` 是我们在搭建SSLRec的临时文件，不会被框架用到。

最后关于数据说明文档📝，我们正在弄啦， 后续会尽快上传，希望可以帮到你 :)

Best regards,
Xubin

**Comment by marqu22** [comment]
非常感谢您的回复，谢谢您

**Comment by toufuheyu** [comment]
那请问生成 meta_multi_single_beh_user_index_shuffle 有具体的规则吗？选取的比例有要求吗？

**Comment by Re-bin** [comment]
嗨！👋

感谢对SSLRec和CML的关注！没有严格的规则，可以尝试选择交互比较多的用户，比例的话可以参考当前数据集中的比例，性能合适即可:)

Best regards,
Xubin

**Comment by toufuheyu** [comment]
好的，非常感谢您的解答！

我首先尝试了在你们的框架中 用SMBRec 跑了跑其他数据集（Taobao ），但是训练速度很慢，在3090的卡上一个Epoch就快跑了半个小时
<img width="837" alt="20240516161546" src="https://github.com/HKUDS/SSLRec/assets/110077582/e824c89b-2fc5-4f30-8d7c-41adbe5c9698">
想知道你们在其他数据集上的训练速度如何？还是我哪里配置出了问题。
SMBRec 经常被用作 baseline 进行比较，但是作者在论文中没有公开代码，你们是根据论文自己实现的 SMBRec 的吗？如果有原始代码的话，能不能发我一份，我的邮箱是： toufuheyu@gmail.com
非常感谢！

**Comment by Re-bin** [comment]
嗨 👋 感谢关注！

1. 多行为推荐算法的训练目前确实比较慢，如果发现代码中有可以优化的地方非常欢迎提PR，一起改进；
2. SMBRec的代码是依据论文描述进行实现的，如果需要原始代码需要联系原始团队尝试获取。

希望上述回复可以帮到您 :)

Best regards,
Xubin
