### ISSUE TITLE
如何构建自己的数据集

### ISSUE THREAD

**Issue by usernameAI** [HKUDS/SSLRec#31]
很棒的工作，非常感谢贵团队开源的代码。

我们希望能够在更多数据集上进行实验，然而，我们没有找到关于数据集文件的说明，例如datasets/social/epinions/下的所有文件，我们不知道应该如何基于自己的数据集生成框架所需的数据文件

非常期待贵团队的回复~

**Comment by Re-bin** [comment]
嗨 👋！

感谢您对SSLRec的认可和关注！以下是关于social recommendation中的数据format的介绍：
- `trn/tst_mat.pkl`: 训练集和测试集，是维度为`[num_user, num_item]`的scipy稀疏矩阵（coo_matrix）。矩阵为01矩阵，entry为1的entry标注一次交互。
- `trust_mat.pkl`: 社交关系，维度为`[num_user, num_user]`的稀疏矩阵，非零的entry标注了两个用户存在社交关系。
- `category.pkl`：商品类别，维度为`[num_item, num_category]`的稀疏矩阵，标记了商品所属的类别（可能多个）。
- `trn_time.pkl`：维度为`[num_user, num_item]`的稀疏矩阵，标注了训练集中交互的时间戳（矩阵entry的value）。

希望上述回答可帮到您 :)

Best regards,
Xubin

**Comment by usernameAI** [comment]
非常感谢贵团队的回复~
