### ISSUE TITLE
关于其他数据集

### ISSUE THREAD

**Issue by cutefishh** [HKUDS/SSLRec#33]
对于general_cf文件夹下的模型，如果我想在yelp数据集下比较性能，请问可以提供下各个模型的最佳超参数设置吗？

**Comment by Re-bin** [comment]
Hi 👋！

感谢关注！目前暂时没有在yelp和amazon上面tune过所有的模型，不过有一部分的结果，可以参考这个[issue](https://github.com/HKUDS/SSLRec/issues/32)。其中也提到了如何实现自动化的参数搜索。

希望可以帮到您 :)

Best regards,
Xubin

**Comment by cutefishh** [comment]
感谢回复！
