### ISSUE TITLE
pickle加载文件时报错ModuleNotFoundError: No module named 'scipy.sparse._csr'，scipy库版本为1.7.3，希望得到作者的解答，万分感谢

### ISSUE THREAD

**Issue by ZZZWWL** [HKUDS/SSLRec#34]
作者您好：
       我在复现多行为模型kmclr时使用pickle.load加载数据集文件出现如下报错：

Traceback (most recent call last):
  File "C:\Users\zwl\Downloads\SSLRec-main\data_utils\data_handler_multi_behavior.py", line 49, in _load_data
    data = pickle.load(fs)
ModuleNotFoundError: No module named 'scipy.sparse._csr'

       而且我的scipy库版本也是1.7.3。请问您知道这是为什么吗？期待您的答复

**Comment by Re-bin** [comment]
嗨 👋！

感谢关注，可以重新创建一个环境并且尝试一下`scipy==1.9.3`，单独把文件复制出来看一下能否用pickle读取。希望可以帮到您 :)

Best regards,
Xubin
