### ISSUE TITLE
关于retail_rocket数据集下生成的kg.txt的含义

### ISSUE THREAD

**Issue by Yaoyuanzhou** [HKUDS/SSLRec#35]
你好，不是很明白你数据集下面几个pkl的各列的含义，以及生成的kg.txt有三列，请问分别代表什么含义呢。能否大概给一个数据集的解释呢。望回复，十分感谢

**Comment by Yaoyuanzhou** [comment]
此外还有个meta_multi_single_beh_user_index_shuffle文件，请问这些已经处理好的数据代表什么呢

**Comment by Yaoyuanzhou** [comment]
<img width="284" alt="image" src="https://github.com/HKUDS/SSLRec/assets/42318410/02155904-a76b-49ef-9d8a-ff37685c3c00">
zhe这些训练和测试文件是怎么根据row data构建来的呢（这部分有代码么），每列代表什么含义呢

**Comment by Re-bin** [comment]
嗨 👋！

感谢关注！文件`kg.txt`是依据`dataprocessing.py`生成的，其是为了记录一个item-item的异构边graph，因此三列中的第一列和第三列都是item_id，然后第二列是behavior_id，表示两个item都有这个behavior的记录（并且大于一定的阈值）。

关于`train_mat_{behavior(s)}.pkl`文件，可以参考一下这个[issue](https://github.com/HKUDS/SSLRec/issues/30)，其存储的都是维度为`[num_user, num_item]`的稀疏矩阵（coo matrix），其主要是记录user-item在特定behavior下的交互（多个behavior即为交集），数值大于0的entry表示了一次交互的存在。（具体数值在代码中最终都是当作1处理，可以参考[代码](https://github1s.com/HKUDS/SSLRec/blob/main/data_utils/data_handler_multi_behavior.py)73行）。

测试数据test_mat.pkl也是一个`[num_user, num_item]`的稀疏矩阵，表示了你target的behavior，一般就是利用buy行为来构建。

希望可以帮到您 :)

Best regards,
Xubin
