### ISSUE TITLE
关于lightgcn层数问题

### ISSUE THREAD

**Issue by cutefishh** [HKUDS/SSLRec#36]
你好！感谢您的出色工作！
请问如果我想比较不同模型在某个数据集上的性能，我需要控制它们的lightgcn层数相同吗? 还是分别取最优情况即可

**Comment by Re-bin** [comment]
嗨 👋！

感谢关注！一般来说模型的层数是可以根据不同数据集进行调整的，没有特殊的限制，除非您的算法需要在固定的层数下进行公平的比较。

希望可以帮到您 :)

Best regards,
Xubin

**Comment by cutefishh** [comment]
谢谢您的回答！之前阅读贵组的文章发现比较不同模型性能的时候，最后一列有个p-value值，请问它是如何计算得到的？

**Comment by Re-bin** [comment]
你好！

p-value是显著性指标，可以用单边t检验的方式计算 :)

Best regards,
Xubin

**Comment by cutefishh** [comment]
感谢您的回答！
