### ISSUE TITLE
cuda版本问题

### ISSUE THREAD

**Issue by wangyingshuai111** [HKUDS/SSLRec#39]
作者您好
请问需要cuda版本是多少，我安装了cuda10.0，提示不能用。另外，这个代码需要GPU吗，最小多大的GPU可以跑？

**Comment by Re-bin** [comment]
嗨 👋！

感谢关注！我们开发使用的CUDA版本是 >= 11.5，然后GPU使用的是3090 24GB版本 :)

Best regards,
Xubin
