### ISSUE TITLE
关于SSLRec运行时出现“Cuda Kernel Error”？

### ISSUE THREAD

**Issue by XChuckie** [HKUDS/SSLRec#40]
- 问题描述：直接运行SSLRec中的LightGCN代码，调试到EdgeDrop是出现“Cuda Kernel Error”，作者有知道原因吗？如下是报错图片以及GPU使用情况：
![image](https://github.com/HKUDS/SSLRec/assets/72149935/0f5edc57-b195-441c-abd4-8147ef6b8f1b)
![image](https://github.com/HKUDS/SSLRec/assets/72149935/7852a98e-a0b5-4509-891c-e62ebda751e3)
- 测试环境描述：
   - torch==1.11.0
   - scipy==1.11.4
   - numpy==1.26.4

**Comment by XChuckie** [comment]
更新：
上述问题出现在AutoDL云平台中的2080ti性能卡中，但使用3090性能卡时又不会出现此问题，这让我很疑惑🤣? 问题：请问贵团队是否在其它性能卡中测试过SSLrec代码呢？可以帮忙解惑一下嘛，不胜感激🙏。

**Comment by Re-bin** [comment]
嗨 👋！

感谢关注SSLRec！我们测试环境确实用的是RTX 3090。

不过一般这种报错是出现了访问越界，看上去28行好像是单独加上去的，原始的edgedrop的代码里面没有这一行代码，会不会注释之后，或许可以正常运行。

希望能帮到你 :)

Best regards,
Xubin

**Comment by XChuckie** [comment]
非常感谢[Re-bin](https://github.com/Re-bin)的回答👏，这种现象看上去是随机性的(或者说是性能卡本身原因)，刚测试AutoDL云平台中其他2080ti性能卡时，该现象不在存在😂.

**Comment by Re-bin** [comment]
好的，感谢您对SSLRec的关注！如果有后续有改进意见和改进代码，欢迎提issue和pr :)

Best regards,
Xubin
