### ISSUE TITLE
关于构建自己的kg数据集

### ISSUE THREAD

**Issue by zzzzljaa** [HKUDS/SSLRec#41]
非常感谢贵团队开源的代码！阅读之后收获颇丰！

我们希望能在其它更多的数据集上进行实验，但是苦于没有数据集文件生成的相关说明，如datasets/kg下各个数据集生成的详细过程，因此我无法生成其它数据集的相关文件。期待贵团队回复❤十分感谢！

**Comment by Re-bin** [comment]
嗨 👋！

感谢对SSLRec的关注！我们正在准备数据集文件说明，以下是关于KG部分的，供你参考 🤗
- `train.txt` This file contains the observed user-item interactions for training. Each line starts with a User ID, followed by the IDs of items that the user has interacted with.
- `test.txt` This file contains the user-item interactions for testing. Each line starts with a User ID, followed by the IDs of items that the user has interacted with.
- `kg_final.txt` This file contains the KG tripltes. Each line of the record follows the format `[item_id, relation_id, entry_id]`.
- `item_list.txt` This file contains the item ID information, which includes `org_id`, `remap_id` and `freebase_id`.
- `entity_list.txt` This file contains the entity ID information, which includes `freebase_id` and `remap_id`.
- `user_list.txt` This file contains the user ID information, which includes `org_id` and `remap_id`
- `relation_list.txt` This file contains the relation ID information, which includes `org_id` and `remap_id`

希望可以帮到你 :)

Best regards,
Xubin

**Comment by zzzzljaa** [comment]
感谢回复❀
