### ISSUE TITLE
关于模型评测指标数值的问题

### ISSUE THREAD

**Issue by toufuheyu** [HKUDS/SSLRec#42]
您好！ 我发现在相同的数据集（Retail Rocket dataset）下，SSLRec 和 原始论文（CML）的 Metrics （NDCG@10）数值量级差距比较大，这是为什么呢？
原始论文：
<img width="1181" alt="cml" src="https://github.com/HKUDS/SSLRec/assets/110077582/9627d4c3-6c10-4bb4-b214-c96ed77ebab4">

SSLRec：
<img width="545" alt="sslrec" src="https://github.com/HKUDS/SSLRec/assets/110077582/01a5c0f5-68ea-41f3-83a0-c7368a35136f">

**Comment by Re-bin** [comment]
嗨 👋

感谢关注呀！这个主要是因为evaluation protocol的不同，具体可以参考一下这个[issue](https://github.com/HKUDS/SSLRec/issues/29)。

希望可以帮到您:)

Best regards,
Xubin
