### ISSUE TITLE
关于HMG-CR的小疑问

### ISSUE THREAD

**Issue by sunshixx** [HKUDS/SSLRec#46]
十分感谢SSLRec提供的开源代码，最近在复现其中一些多行为模型的时候遇到了一些问题。
在这里（hmgcr.py）self.embed_list_user, self.embed_list_item = [], []
        self.meta_embed_list_user, self.meta_embed_list_item = [], []都重置了，那么后续self._batched_contrastive_loss算不出来。导致训练的时候cl_loss是0
![微信图片_20240812215840](https://github.com/user-attachments/assets/8d311082-c7b9-496e-98ad-3804471ded12)
![image](https://github.com/user-attachments/assets/6d0af541-066e-459f-b26b-b7bba20ddcd8)

**Comment by Re-bin** [comment]
嗨 👋 你好！

十分感谢您对SSLRec的关注以及改进建议！目前已经根据您的建议，对合作者提供的hmgcr代码进行了更新，后续会进一步测试这个baseline，如果还有别的发现或建议还请告诉我们，再次感谢 :)

Best regards,
Xubin
