### ISSUE TITLE
About KG Data

### ISSUE THREAD

**Issue by Lightblues** [HKUDS/SSLRec#5]
您好! 
我在看KG的模型, 发现eval似乎又个bug? KGTestDataset中只返回了u但是在eval中调用的是 <u,i>. 
抱歉还没有细看评测的代码, 希望能拨冗解答, 祝好🙏

```python
# dataset_kg.py
class KGTestDataset(data.Dataset):
    def __init__(self, test_user_dict) -> None:
        self.user_pos_lists = test_user_dict
        self.test_users = np.array(list(test_user_dict.keys()))

    def __getitem__(self, idx):
        return self.test_users[idx]

# metrics.py
class Metric(object):
    def eval_at_one_forward(self, model, test_dataloader):
        for _, tem in enumerate(test_dataloader):
            batch_u, batch_i = batch_data[:2]
``` 

另, 有一个问题想咨询, 我想做一个融合KG的Sequential模型, 不知道在本框架下, 关于数据集的格式上您是否有建议? (以及您是否了解相关的 KG+SRS 的数据?)

**Comment by yuh-yang** [comment]
你好，感谢你的feedback，已于[23cb7da](https://github.com/HKUDS/SSLRec/commit/23cb7dad0f667a8e83b418bb84e630cabed22861)修复此问题。这个问题不影响模型训练，你可以直接重新评测已有的checkpoint。

对于KG+SRS，可以参考一下我们的另一个工作[MBHT-KDD22](https://github.com/yuh-yang/MBHT-KDD22)，关于多行为模式下的sequential rec，其中采用的数据格式同样兼容Recbole库。也可以采用当前KGRec使用的kg.txt这种格式，在模型里面写聚合逻辑就OK

**Comment by Lightblues** [comment]
好的好的，我去看看那篇工作！感谢！
