### ISSUE TITLE
[Warning Report] "is" with a literal

### ISSUE THREAD

**Issue by HeyWeCome** [HKUDS/SSLRec#6]
Hello, thank you for your valuable work.

**Problem description**:
I found the following warning when running the project by `python main.py --model LightGCN --device 'cpu'`:
`
/SSLRec/models/loss_utils.py:96: SyntaxWarning: "is" with a literal. Did you mean "=="? if reduce is 'mean':
`

**Problem cause**:
Starting from Python 3.8, using "is" and "is not" operators will raise a SyntaxWarning.

**Problem solution**:
Replace "is" and "is not" with "=="" and "!="" in the corresponding statements.

By the way, there is also another RuntimeWarning in /SSLRec/data_utils/data_handler_general_cf.py:47:
`RuntimeWarning: divide by zero encountered in power 
d_inv_sqrt = np.reshape(np.power(degree, -0.5), [-1])`

It seems that there is a zero in the data.

**Comment by HeyWeCome** [comment]
A cleaner approach is to add a small epsilon to the degree to avoid zeros, before taking the reciprocal square root.

Here is  one way I provide to fix it:

```python
def _normalize_adj(self, mat):
    # Add epsilon to avoid divide by zero
    degree = np.array(mat.sum(axis=-1)) + 1e-10
    d_inv_sqrt = np.reshape(1.0 / np.sqrt(degree), [-1])
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.0
    d_inv_sqrt_mat = sp.diags(d_inv_sqrt)
    return mat.dot(d_inv_sqrt_mat).transpose().dot(d_inv_sqrt_mat).tocoo()
```

By adding a small epsilon value, it guarantees there are no zeros in degree, avoiding the divide by zero.

The tiny epsilon doesn't meaningfully change the normalization, but avoids the need to handle inf/NaN values separately.

I hope it will help. By the way, I wanted to mention that I originally intended to submit code to a `dev` branch, but noticed that the project only has a master branch. In the future, would you consider adding a dev branch or something similar to facilitate the contributions? Thank you.

**Comment by Re-bin** [comment]
Hi!

Thanks for your interest in SSLRec, and we appreciate your contribution! 
Perhaps you could consider submitting a pull request so that we can merge your changes into the project ;)

Best regards,
Xubin

**Comment by HeyWeCome** [comment]
Of course, I am more than happy to make a contribution. Currently, I have already submitted a pull request #7. If there are any issues with the code, please let me know. Thanks.

**Comment by Re-bin** [comment]
Hi! Thank you for your contribution. It has been merged into the main branch :)

**Comment by HeyWeCome** [comment]
Thank you for your recognition, good night~
